const LOG_LEVELS = ["trace", "debug", "info", "warn", "error"];
const STRATEGIES = [
  { value: "priority_weighted", label: "优先级内加权（推荐）" },
  { value: "priority", label: "仅优先级" },
  { value: "weighted_round_robin", label: "加权轮询" },
  { value: "round_robin", label: "轮询" },
];
const REASONING_LEVELS = [
  "default",
  "off",
  "minimal",
  "low",
  "medium",
  "high",
];
const OPENAI_REASONING = [
  "inherit",
  "default",
  "none",
  "minimal",
  "low",
  "medium",
  "high",
  "xhigh",
  "max",
];
const GEMINI_THINKING = [
  "inherit",
  "default",
  "off",
  "minimal",
  "low",
  "medium",
  "high",
];

const routeOptions = { paths: ["ai.routes"], valueKey: "id" };
const profileOptions = { paths: ["ai.profiles"], valueKey: "name" };
const roleCardOptions = { paths: ["ai.roleCards"], valueKey: "name" };
const providerOptions = { paths: ["ai.providers"], valueKey: "id" };

const credentialFields = [
  { key: "id", label: "凭据 ID", type: "text" },
  {
    key: "apiKey",
    label: "API Key",
    type: "secret",
    help: "直接填写并保存到 config/config.yaml；面板会遮罩已保存的密钥。",
  },
  {
    key: "serviceAccountRef",
    label: "Vertex 凭据引用",
    type: "text",
    help: "填写 data/ai/vertex-credentials 下的 JSON 文件名（不含扩展名也可按现有约定填写）。",
  },
  { key: "enabled", label: "启用", type: "boolean" },
  { key: "priority", label: "优先级", type: "number", step: 1 },
  { key: "weight", label: "权重", type: "number", min: 1, max: 100 },
];

const routeTargetFields = [
  { key: "id", label: "目标 ID", type: "text" },
  {
    key: "provider",
    label: "供应商",
    type: "select",
    optionsFrom: providerOptions,
    allowEmpty: false,
    allowCustom: false,
    clearOnChange: ["model"],
    placeholder: "请选择供应商",
    help: "只能从已配置的文本模型供应商中选择。",
  },
  {
    key: "model",
    label: "模型",
    type: "modelSelect",
    providerField: "provider",
    allowCustom: false,
    help: "根据所选供应商的模型端点动态加载，只能从返回结果中选择。",
  },
  { key: "enabled", label: "启用", type: "boolean" },
  { key: "priority", label: "优先级", type: "number", step: 1 },
  { key: "weight", label: "权重", type: "number", min: 1, max: 100 },
  {
    key: "temperatureOverride",
    label: "Temperature 覆盖",
    type: "number",
    min: -1,
    max: 2,
    step: 0.1,
    help: "-1 表示沿用路由设置。",
  },
  {
    key: "topPOverride",
    label: "Top P 覆盖",
    type: "number",
    min: -1,
    max: 1,
    step: 0.05,
  },
  {
    key: "openaiEnableThinking",
    label: "OpenAI Thinking",
    type: "boolean",
  },
  {
    key: "openaiReasoningEffort",
    label: "OpenAI 推理强度",
    type: "select",
    options: OPENAI_REASONING,
  },
  {
    key: "geminiThinkingLevel",
    label: "Gemini 思考等级",
    type: "select",
    options: GEMINI_THINKING,
  },
  {
    key: "geminiThinkingBudget",
    label: "Gemini 思考预算",
    type: "number",
    min: -2,
    step: 1,
    help: "-2 表示沿用默认行为。",
  },
];

const novelAIFields = [
  {
    key: "model",
    label: "模型",
    type: "text",
    placeholder: "nai-diffusion-5-full",
  },
  {
    key: "baseURL",
    label: "API 地址",
    type: "url",
    placeholder: "https://image.novelai.net",
  },
  {
    key: "api",
    label: "NovelAI Token",
    type: "secret",
    placeholder: "直接填写 NovelAI Token",
  },
  {
    key: "checkV5Usage",
    label: "检查 V5 用量",
    type: "boolean",
    help: "仅在符合零 Anlas 条件时自动回退 V4.5。",
  },
  { key: "negative", label: "负面提示词", type: "textarea", rows: 5 },
  { key: "qualityTags", label: "质量标签", type: "textarea", rows: 3 },
  {
    key: "width",
    label: "默认宽度",
    type: "number",
    min: 64,
    max: 2048,
    step: 64,
  },
  {
    key: "height",
    label: "默认高度",
    type: "number",
    min: 64,
    max: 2048,
    step: 64,
  },
  {
    key: "scale",
    label: "Prompt Guidance",
    type: "number",
    min: 0,
    max: 10,
    step: 0.1,
  },
  {
    key: "steps",
    label: "采样步数",
    type: "number",
    min: 1,
    max: 50,
    step: 1,
  },
  { key: "sampler", label: "采样器", type: "text" },
  {
    key: "strength",
    label: "图生图强度",
    type: "number",
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: "noise",
    label: "图生图噪声",
    type: "number",
    min: 0,
    max: 1,
    step: 0.05,
  },
];

export const CONFIG_UI_SCHEMA = {
  version: 7,
  title: "SakuraTG 配置中心",
  description: "专用于 Telegram 角色扮演、短期历史和 NovelAI 绘图",
  categories: [
    { id: "core", label: "基础服务" },
    { id: "roleplay", label: "角色扮演" },
    { id: "novelai", label: "NovelAI" },
  ],
  sections: [
    {
      id: "general",
      category: "core",
      title: "运行设置",
      icon: "◈",
      root: "",
      fields: [
        {
          key: "logLevel",
          label: "日志等级",
          type: "select",
          options: LOG_LEVELS,
        },
      ],
    },
    {
      id: "telegram",
      category: "core",
      title: "Telegram",
      icon: "✦",
      root: "telegram",
      description: "Bot API 连接、主人和访问控制。Token 或 API 地址变更后需重启。",
      fields: [
        {
          key: "token",
          label: "Bot Token",
          type: "secret",
          restartRequired: true,
        },
        {
          key: "apiRoot",
          label: "Bot API 地址",
          type: "url",
          restartRequired: true,
        },
        { key: "masters", label: "主人 ID", type: "numberList" },
        { key: "whiteUsers", label: "用户白名单", type: "numberList" },
        { key: "whiteChats", label: "会话白名单", type: "numberList" },
        { key: "blackUsers", label: "用户黑名单", type: "numberList" },
        { key: "blockPrivate", label: "屏蔽私聊", type: "boolean" },
        {
          key: "dropPendingUpdates",
          label: "启动时丢弃离线消息",
          type: "boolean",
          restartRequired: true,
        },
        {
          key: "localApiServer",
          label: "使用本地 Bot API Server",
          type: "boolean",
        },
      ],
    },
    {
      id: "redis",
      category: "core",
      title: "Redis",
      icon: "◆",
      root: "redis",
      description: "短期角色对话历史存储。该区域变更后需重启。",
      fields: [
        { key: "host", label: "地址", type: "text", restartRequired: true },
        {
          key: "port",
          label: "端口",
          type: "number",
          min: 1,
          max: 65535,
          restartRequired: true,
        },
        {
          key: "password",
          label: "密码",
          type: "secret",
          restartRequired: true,
        },
        {
          key: "execPath",
          label: "本地 Redis 路径",
          type: "text",
          restartRequired: true,
          help: "可填写 redis-server.exe 或所在目录；仅回环地址且端口未监听时自动启动。",
        },
        {
          key: "db",
          label: "数据库编号",
          type: "number",
          min: 0,
          max: 15,
          restartRequired: true,
        },
      ],
    },
    {
      id: "web",
      category: "core",
      title: "配置面板",
      icon: "▣",
      root: "web",
      fields: [
        {
          key: "enabled",
          label: "启用面板",
          type: "boolean",
          restartRequired: true,
        },
        { key: "host", label: "监听地址", type: "text", restartRequired: true },
        {
          key: "port",
          label: "监听端口",
          type: "number",
          min: 1,
          max: 65535,
          restartRequired: true,
        },
        { key: "password", label: "登录密码", type: "secret" },
      ],
    },
    {
      id: "ai-general",
      category: "roleplay",
      title: "对话设置",
      icon: "✺",
      root: "ai",
      description: "只包含角色扮演、短期历史、原生图片输入和路由参数。",
      fields: [
        { key: "enabled", label: "启用角色扮演", type: "boolean" },
        {
          key: "privateAutoReply",
          label: "私聊自动回复",
          type: "boolean",
        },
        {
          key: "defaultProfile",
          label: "默认角色",
          type: "select",
          optionsFrom: profileOptions,
          allowEmpty: true,
          allowCustom: false,
          help: "从当前角色运行配置中选择；新增、改名或删除后候选会同步变化。",
        },
        {
          key: "chatHistoryLength",
          label: "短期历史轮数",
          type: "number",
          min: 0,
          max: 100,
        },
        {
          key: "historyTtlSeconds",
          label: "历史保留秒数",
          type: "number",
          min: 3600,
          max: 7776000,
        },
        {
          key: "enableUserLock",
          label: "同用户请求互斥",
          type: "boolean",
        },
        {
          key: "requestTimeoutMs",
          label: "模型请求超时（毫秒）",
          type: "number",
          min: 1000,
          max: 1800000,
          step: 1000,
        },
      ],
    },
    {
      id: "role-cards",
      category: "roleplay",
      title: "角色卡",
      icon: "♕",
      root: "ai.roleCards",
      type: "array",
      itemLabel: "角色卡",
      itemKey: "name",
      template: {
        name: "",
        prompt: "",
      },
      fields: [
        { key: "name", label: "名字", type: "text" },
        {
          key: "prompt",
          label: "角色设定",
          type: "textarea",
          rows: 12,
        },
      ],
    },
    {
      id: "profiles",
      category: "roleplay",
      title: "角色运行配置",
      icon: "♙",
      root: "ai.profiles",
      type: "array",
      itemLabel: "角色配置",
      itemKey: "name",
      template: {
        name: "",
        prefixes: [],
        keepTriggerPrefix: false,
        route: "",
        history: true,
        enableNaiPainting: false,
        naiPrompt: "",
        enabled: true,
      },
      fields: [
        {
          key: "name",
          label: "角色卡",
          type: "select",
          optionsFrom: roleCardOptions,
          allowEmpty: false,
          allowCustom: false,
          placeholder: "请选择角色卡",
          help: "从已有角色卡中选择；请先在角色卡页面新增角色。",
        },
        { key: "prefixes", label: "触发前缀", type: "stringList" },
        {
          key: "keepTriggerPrefix",
          label: "向模型保留触发前缀",
          type: "boolean",
          help: "开启后，“小叶你好”会完整提交给模型；关闭后只提交“你好”。仅影响普通角色前缀触发。",
        },
        {
          key: "route",
          label: "模型路由",
          type: "select",
          optionsFrom: routeOptions,
          allowEmpty: false,
          allowCustom: false,
          placeholder: "请选择模型路由",
          help: "只能从已配置的模型路由中选择。",
        },
        { key: "history", label: "启用短期历史", type: "boolean" },
        {
          key: "enableNaiPainting",
          label: "启用 RP 自动配图",
          type: "boolean",
          help: "隐藏模型输出的 <draw> 标签，并在后台最多生成一次图片；发送 /lastdraw 可查看上一次标签。",
        },
        {
          key: "naiPrompt",
          label: "固定绘图标签",
          type: "textarea",
          rows: 4,
        },
        { key: "enabled", label: "启用角色", type: "boolean" },
      ],
    },
    {
      id: "providers",
      category: "roleplay",
      title: "文本模型供应商",
      icon: "⬡",
      root: "ai.providers",
      type: "array",
      itemLabel: "供应商",
      itemKey: "id",
      template: {
        id: "",
        protocol: "openai",
        baseURL: "",
        vertex: false,
        credentials: [
          {
            id: "",
            apiKey: "",
            serviceAccountRef: "",
            enabled: false,
            priority: 0,
            weight: 1,
          },
        ],
      },
      fields: [
        { key: "id", label: "供应商 ID", type: "text" },
        {
          key: "protocol",
          label: "协议",
          type: "select",
          options: ["openai", "gemini"],
        },
        { key: "baseURL", label: "API 地址", type: "url" },
        { key: "vertex", label: "使用 Vertex AI", type: "boolean" },
        {
          key: "credentials",
          label: "凭据池",
          type: "array",
          itemLabel: "凭据",
          itemKey: "id",
          template: {
            id: "",
            apiKey: "",
            serviceAccountRef: "",
            enabled: false,
            priority: 0,
            weight: 1,
          },
          fields: credentialFields,
          minItems: 1,
        },
      ],
    },
    {
      id: "routes",
      category: "roleplay",
      title: "模型路由",
      icon: "⌁",
      root: "ai.routes",
      type: "array",
      itemLabel: "路由",
      itemKey: "id",
      template: {
        id: "",
        strategy: "priority_weighted",
        temperature: -1,
        topP: -1,
        reasoningLevel: "default",
        maxAttempts: 3,
        retryDelayMs: 1000,
        targets: [
          {
            id: "",
            provider: "",
            model: "",
            enabled: true,
            priority: 0,
            weight: 1,
            temperatureOverride: -1,
            topPOverride: -1,
            openaiEnableThinking: false,
            openaiReasoningEffort: "inherit",
            geminiThinkingLevel: "inherit",
            geminiThinkingBudget: -2,
          },
        ],
      },
      fields: [
        { key: "id", label: "路由 ID", type: "text" },
        {
          key: "strategy",
          label: "调度策略",
          type: "select",
          options: STRATEGIES,
        },
        {
          key: "temperature",
          label: "Temperature",
          type: "number",
          min: -1,
          max: 2,
          step: 0.1,
        },
        {
          key: "topP",
          label: "Top P",
          type: "number",
          min: -1,
          max: 1,
          step: 0.05,
        },
        {
          key: "reasoningLevel",
          label: "统一推理等级",
          type: "select",
          options: REASONING_LEVELS,
        },
        {
          key: "maxAttempts",
          label: "最大尝试次数",
          type: "number",
          min: 1,
          max: 50,
        },
        {
          key: "retryDelayMs",
          label: "回退间隔（毫秒）",
          type: "number",
          min: 0,
          max: 60000,
        },
        {
          key: "targets",
          label: "路由目标",
          type: "array",
          itemLabel: "目标",
          itemKey: "id",
          template: {
            id: "",
            provider: "",
            model: "",
            enabled: true,
            priority: 0,
            weight: 1,
            temperatureOverride: -1,
            topPOverride: -1,
            openaiEnableThinking: false,
            openaiReasoningEffort: "inherit",
            geminiThinkingLevel: "inherit",
            geminiThinkingBudget: -2,
          },
          fields: routeTargetFields,
          minItems: 1,
        },
      ],
    },
    {
      id: "native-vision",
      category: "roleplay",
      title: "原生图片输入",
      icon: "◉",
      root: "ai.nativeVision",
      description: "仅限制当前消息及其回复中的图片；图片直接沿普通模型路由提交，不调用识图工具，也不会写入 Redis 历史。",
      fields: [
        {
          key: "maxImages",
          label: "单轮最多图片数",
          type: "number",
          min: 0,
          max: 10,
        },
        {
          key: "maxBytes",
          label: "单轮图片总字节数",
          type: "number",
          min: 1024,
          max: 104857600,
        },
      ],
    },
    {
      id: "novelai",
      category: "novelai",
      title: "NovelAI 绘图",
      icon: "◐",
      root: "ai.novelAI",
      description: "显式绘图、图生图、Vibe Transfer 和 RP 的 <draw> 自动配图。",
      fields: [
        { key: "enabled", label: "启用 NovelAI", type: "boolean" },
        ...novelAIFields,
        {
          key: "chatDrawPrompt",
          label: "RP 绘图指令",
          type: "textarea",
          rows: 14,
        },
        {
          key: "chatDrawWidth",
          label: "RP 配图宽度",
          type: "number",
          min: 64,
          max: 2048,
          step: 64,
          help: "NovelAI 原生宽度，必须是 64 的倍数。",
        },
        {
          key: "chatDrawHeight",
          label: "RP 配图高度",
          type: "number",
          min: 64,
          max: 2048,
          step: 64,
          help: "NovelAI 原生高度，必须是 64 的倍数。",
        },
        {
          key: "chatDrawCount",
          label: "每轮配图数量",
          type: "number",
          min: 1,
          max: 4,
          help:
            "同一轮最多触发一次绘图；多张会拆成串行单张请求，每张生成后立即发送，发送不阻塞下一张生成。",
        },
      ],
    },
  ],
};
